# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-03 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_mail', '0004_auto_20170320_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlist',
            name='country',
            field=models.CharField(blank=True, max_length=35, verbose_name='Страна отправления'),
        ),
        migrations.AddField(
            model_name='requestlist',
            name='data_sending',
            field=models.CharField(blank=True, max_length=35, verbose_name='Дата поездки'),
        ),
        migrations.AddField(
            model_name='requestlist',
            name='days',
            field=models.CharField(blank=True, max_length=20, verbose_name='Продолжительность поездки'),
        ),
        migrations.AddField(
            model_name='requestlist',
            name='food',
            field=models.CharField(blank=True, max_length=140, verbose_name='Питание'),
        ),
        migrations.AddField(
            model_name='requestlist',
            name='people',
            field=models.CharField(blank=True, max_length=140, verbose_name='Колличество человек'),
        ),
        migrations.AddField(
            model_name='requestlist',
            name='price',
            field=models.CharField(blank=True, max_length=35, verbose_name='Цена'),
        ),
    ]
